server:
  port: 3033

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CORE-SERVICE
          uri: lb://CORE-SERVICE
          predicates:
            - Path=/core/**
        - id: SCHEDULE-SERVICE
          uri: lb://SCHEDULE-SERVICE
          predicates:
           - Path=/schedule/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost